// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PhoneNum   string `json:"phoneNum"`
	Avatar     string `json:"avatar"`
	CardNumber string `json:"cardNumber"`
	Balance    *int   `json:"balance,omitempty"`
}
